version: '3'
services :
    ride_call:
        container_name: rides
        restart: always
        build:
            context: ./Rides
            dockerfile: Dockerfile
        image: rides:latest
        ports:
          - "80:5000"
