version: '3.1'
services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  rmq:
    image: rabbitmq:3.8.3-alpine
    hostname: "rmq"

  orchestrator:
    build:
      context: ./Project
      dockerfile: Dockerfile
    command: sh -c "sleep 20 && python3 orches.py"
    ports:
    - "80:5000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - rmq
    - zoo
    restart: on-failure
  
  master:
    build:
      context: ./Project
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && python3 worker.py"
    environment:
    - TYPE=master
    - NAME=ubuntu_master_1
    depends_on:
    - rmq
    - zoo
    restart: on-failure
  
  slave:
    build:
      context: ./Project
      dockerfile: Dockerfile
    command: sh -c "sleep 35 && python3 worker.py"
    environment:
    - TYPE=slave
    - NAME=ubuntu_slave_1
    depends_on:
    - rmq
    - zoo
    restart: on-failure


